name: pulling_env
channels:
  - conda-forge
  - omnia
  - defaults
dependencies:
  - ipython>=8.16.1
  - jupyter>=1.0.0
  - matplotlib>=3.8.0
  - mdtraj=1.9.9
  - numpy>=1.26.0
  - openmm>=8.0.0
  - pandas>=2.1.2
  - scikit-learn>=1.3.2
  - scipy>=1.11.3
